# Generated by Django 5.0.4 on 2026-04-28 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_type', models.CharField(choices=[('affordability', 'Can I Afford This?'), ('goal_impact', 'Goal Impact'), ('safe_spend', 'Safe to Spend'), ('emi_vs_cash', 'EMI vs Cash'), ('rent_vs_buy', 'Rent vs Buy')], db_index=True, max_length=20)),
                ('input_data', models.JSONField()),
                ('result_data', models.JSONField()),
                ('verdict', models.CharField(choices=[('SAFE', 'Safe'), ('CAUTION', 'Caution'), ('RISKY', 'Risky')], db_index=True, max_length=10)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AED', 'AED'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('JPY', 'JPY'), ('SGD', 'SGD'), ('BRL', 'BRL')], default='USD', max_length=3)),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='Engine algorithm version — allows A/B testing and result migration.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
