# Generated by Django 5.0.4 on 2026-04-28 07:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixed_expenses', models.DecimalField(decimal_places=2, default=0, help_text='Monthly fixed costs: rent, bills, subscriptions.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_savings', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_emi', models.DecimalField(decimal_places=2, default=0, help_text='Total monthly EMI / loan repayments.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('default_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('AED', 'AED'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('JPY', 'JPY'), ('SGD', 'SGD'), ('BRL', 'BRL')], default='USD', max_length=3)),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('AE', 'UAE'), ('CA', 'Canada'), ('AU', 'Australia'), ('JP', 'Japan'), ('SG', 'Singapore'), ('BR', 'Brazil'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('is_onboarded', models.BooleanField(default=False, help_text='True once user has completed initial profile setup.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
